# Generated by Django 5.0.2 on 2024-02-20 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("currencies", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="currency",
            options={"verbose_name": "currency", "verbose_name_plural": "currencies"},
        ),
    ]
