# Generated by Django 5.0.2 on 2024-03-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("currencies", "0002_alter_currency_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="currency",
            name="position",
            field=models.CharField(default="before", max_length=10),
        ),
    ]
