# Generated by Django 5.0.2 on 2024-02-17 01:13

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                default=None,
                max_length=30,
                null=True,
                region=None,
                verbose_name="phone number",
            ),
        ),
    ]
