ARG NODE_VERSION=20-alpine3.20

FROM node:${NODE_VERSION} as node

FROM node as client-local-build

ARG APP_HOME=/app/frontend

WORKDIR ${APP_HOME}

RUN npm install

COPY . ${APP_HOME}

CMD ["npm","run","dev"]