# Generated by Django 5.0.2 on 2024-02-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audits", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="action",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
