# Generated by Django 5.0.2 on 2024-02-22 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audits", "0003_auditlog_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="new_value",
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="old_value",
            field=models.TextField(default=None, null=True),
        ),
    ]
