# Generated by Django 5.0.2 on 2024-02-20 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userbranch",
            options={
                "verbose_name": "user branch",
                "verbose_name_plural": "User Branch",
            },
        ),
    ]
