# Generated by Django 5.0.2 on 2024-02-21 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_userbranch_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userbranch",
            options={
                "verbose_name": "userbranch",
                "verbose_name_plural": "User Branch",
            },
        ),
    ]
