# Generated by Django 5.0.2 on 2024-02-21 04:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0002_alter_branch_country"),
        ("users", "0003_alter_userbranch_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="active_branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="active_users",
                to="branches.branch",
            ),
        ),
        migrations.AlterField(
            model_name="userbranch",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_branches",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
