# Generated by Django 5.0.2 on 2024-02-24 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_active_branch_alter_userbranch_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [("ban_user", "Can Ban User")],
                "verbose_name": "user",
                "verbose_name_plural": "users",
            },
        ),
    ]
