# Generated by Django 5.0.2 on 2024-02-28 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0003_alter_branch_country_alter_branch_is_active_and_more"),
        ("users", "0005_alter_user_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="branches",
            field=models.ManyToManyField(
                related_name="users", through="users.UserBranch", to="branches.branch"
            ),
        ),
    ]
