# Generated by Django 4.2.4 on 2023-11-09 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_loan_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_loan_term', models.PositiveIntegerField()),
                ('max_loan_term', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Loan Product',
                'verbose_name_plural': 'Loan Products',
            },
        ),
    ]
