# Generated by Django 4.2.7 on 2023-11-22 16:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ref_code",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("loan_term", models.PositiveIntegerField()),
                ("application_date", models.DateField()),
                ("status", models.CharField(max_length=50)),
                ("approval_date", models.DateField(blank=True, null=True)),
                ("disbursement_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Loan",
                "verbose_name_plural": "Loans",
            },
        ),
        migrations.CreateModel(
            name="LoanCollateral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("type", models.CharField(max_length=255)),
                ("value", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                "verbose_name": "Loan Collateral",
                "verbose_name_plural": "Loan Collaterals",
            },
        ),
    ]
