# Generated by Django 4.2.7 on 2023-11-22 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clients", "0002_initial"),
        ("loan_products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("loans", "0001_initial"),
        ("currencies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="loancollateral",
            name="created_by",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="loancollateral",
            name="loan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collaterals",
                to="loans.loan",
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="loans",
                to="clients.client",
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_loans",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="currency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="currencies.currency"
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="loan_product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="loan_products.loanproduct",
            ),
        ),
    ]
