# Generated by Django 5.0.2 on 2024-02-22 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branch_assets", "0001_initial"),
        ("branches", "0002_alter_branch_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="branchassets",
            name="branch",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="branch_assets",
                to="branches.branch",
            ),
        ),
    ]
