# Generated by Django 5.0.2 on 2024-02-22 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branch_assets", "0002_alter_branchassets_branch"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="branchassets",
            name="used_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="used_assets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
