# Generated by Django 5.0.2 on 2024-02-22 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("branch_assets", "0003_alter_branchassets_used_by"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="branchassets",
            options={},
        ),
    ]
