# Generated by Django 5.0.2 on 2024-02-22 15:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branch_assets", "0004_alter_branchassets_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="branchassets",
            name="brand",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="branchassets",
            name="color",
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="branchassets",
            name="item",
            field=models.CharField(
                max_length=255,
                validators=[django.core.validators.MinLengthValidator(3)],
            ),
        ),
    ]
