# Generated by Django 5.0.2 on 2024-02-17 02:39

import django.contrib.postgres.fields
import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("branches", "0001_initial"),
        ("countries", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "first_name",
                    models.CharField(max_length=50, verbose_name="First Name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=50, verbose_name="Last Name"),
                ),
                (
                    "emails",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.EmailField(
                            max_length=254, verbose_name="Email"
                        ),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                        verbose_name="Emails",
                    ),
                ),
                (
                    "national_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="National ID",
                    ),
                ),
                (
                    "nationality",
                    models.CharField(max_length=255, verbose_name="Nationality"),
                ),
                (
                    "passport_number",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Passport Number",
                    ),
                ),
                (
                    "passport_country",
                    django_countries.fields.CountryField(
                        default="ZW", max_length=2, verbose_name="Passport Country"
                    ),
                ),
                (
                    "photo",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Photo"
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date of Birth"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        choices=[
                            ("Dr", "Dr"),
                            ("Miss", "Miss"),
                            ("Mr", "Mr"),
                            ("Mrs", "Mrs"),
                            ("Ms", "Ms"),
                            ("Prof", "Prof"),
                        ],
                        max_length=10,
                        verbose_name="Title",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="Gender",
                    ),
                ),
                (
                    "street_number",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Street Number",
                    ),
                ),
                (
                    "suburb",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Suburb"
                    ),
                ),
                (
                    "zip_code",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="ZIP Code"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="City"
                    ),
                ),
                (
                    "state",
                    models.CharField(max_length=255, verbose_name="State / Province"),
                ),
                (
                    "guarantor",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Guarantor"
                    ),
                ),
                (
                    "is_guarantor",
                    models.BooleanField(default=False, verbose_name="Is Guarantor"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("banned", "Banned"),
                            ("restricted", "Restricted"),
                            ("died", "Died"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="branches.branch",
                        verbose_name="Branch",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="countries.country",
                        verbose_name="Country",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "country_code",
                    models.CharField(max_length=5, verbose_name="Country Code"),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="Phone Number")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Cellphone", "Cellphone"),
                            ("Home", "Home"),
                            ("Work", "Work"),
                            ("Other", "Other"),
                        ],
                        max_length=20,
                        verbose_name="Contact Type",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="Primary"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "whatsapp",
                    models.BooleanField(default=False, verbose_name="WhatsApp"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="clients.client",
                        verbose_name="Client",
                    ),
                ),
            ],
        ),
    ]
