# Generated by Django 4.2.4 on 2023-11-09 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='national_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='passport_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
