# Generated by Django 5.0.2 on 2024-02-17 02:38

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    django_countries.fields.CountryField(
                        default="ZW", max_length=2, verbose_name="country"
                    ),
                ),
                ("alpha2code", models.CharField(max_length=2, unique=True)),
                ("alpha3code", models.CharField(max_length=3, unique=True)),
            ],
        ),
    ]
