# Generated by Django 5.0.2 on 2024-02-20 15:40

import django_countries.fields
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "address",
                    models.TextField(
                        blank=True, max_length=255, verbose_name="address"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        default=None,
                        max_length=254,
                        verbose_name="email address",
                    ),
                ),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        default=None,
                        max_length=30,
                        region=None,
                        verbose_name="phone number",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("country", django_countries.fields.CountryField(max_length=2)),
            ],
            options={
                "verbose_name": "branch",
                "verbose_name_plural": "branches",
            },
        ),
    ]
