# Generated by Django 5.0.2 on 2024-02-17 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="branch",
            options={"verbose_name": "branch", "verbose_name_plural": "branches"},
        ),
    ]
